import "server-only";
import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Shape of public/asset-manifest.json, generated by tools/export/manifest.py.
 * Every field is nullable until the Python asset pipeline has actually run
 * and produced optimized output — components must treat a null/empty
 * entry as "not yet available" rather than assuming a value.
 */
export interface AssetManifest {
  $schemaVersion: number;
  background: string | null;
  sunlightOverlay: string | null;
  wordmark: string | null;
}

const MANIFEST_PATH = path.join(process.cwd(), "public", "asset-manifest.json");

let cached: AssetManifest | null = null;

/**
 * Loads and caches the asset manifest from public/. This is the *only*
 * sanctioned way for server components to resolve hero asset paths —
 * never hardcode a filename in a component; add it to the manifest (via
 * the Python pipeline) and read it from here instead.
 */
export async function loadAssetManifest(): Promise<AssetManifest> {
  if (cached) return cached;
  const raw = await readFile(MANIFEST_PATH, "utf-8");
  cached = JSON.parse(raw) as AssetManifest;
  return cached;
}
